title: Jiahao Chang's Homepage
page-top-title: Jiahao Chang
top-section-bg-text: Nuclear Science
home-subtitle: Jiahao Chang&ensp;|&ensp;常嘉豪
copyright-text: '&copy; Jiahao Chang 2024-2025. All Rights Reserved.'
